<a href="https://colab.research.google.com/github/himanshurao0410/inventory/blob/main/Himanshu_Yadav.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Here I am importing some libraries:




In [3]:
import pandas as pd
import numpy as np

In [5]:
from sklearn.datasets import load_iris
iris_dataset=load_iris()

Above load_iris is function.
it load all the iris dataset.

In [8]:
print("keys of iris_dataset: \n{}",format(iris_dataset.keys()))

keys of iris_dataset: 
{} dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [7]:
 print(iris_dataset['DESCR'][:150]+"\n")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes



Here we are discussing about target_name:

In [10]:
print("Target names: {}".format(iris_dataset['target_names']))

Target names: ['setosa' 'versicolor' 'virginica']


now we are discussing about feature_names:

In [11]:
print("Feature names:\n{}".format(iris_dataset['feature_names']))

Feature names:
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


Now we are looking at type of data: 

In [12]:
print("Type of data:{}".format(iris_dataset['data']))

Type of data:[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]

In [14]:
print("Shape of data:{}".format(iris_dataset['data'].shape))

Shape of data:(150, 4)


In [16]:
print("First four columns of data:\n{}".format(iris_dataset['data'][:4]))

First four columns of data:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]]


In [17]:
print("Type of target:{}".format(type(iris_dataset['target'])))

Type of target:<class 'numpy.ndarray'>


In [18]:
print("shape of target:{}".format(iris_dataset['target'].shape))

shape of target:(150,)


In [19]:
print("Target:\n{}".format(iris_dataset['target']))

Target:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


Testing the data:

In [26]:
from sklearn.model_selection import train_test_split
x_train, x_test,y_train, y_test = train_test_split(
    iris_dataset['data'],iris_dataset['target'], random_state=0)

In [27]:
print("x_train shape:{}".format(x_train.shape))
print("y_train shape:{}".format(y_train.shape))
print("x_test shape:{}".format(x_test.shape))
print("y_test shape:{}".format(y_test.shape))

x_train shape:(112, 4)
y_train shape:(112,)
x_test shape:(38, 4)
y_test shape:(38,)


now we are the analysis:

In [30]:
from sklearn.neighbors import KNeighborsClassifier
kn= KNeighborsClassifier(n_neighbors=1)

Here we training the model which we have created. 

In [31]:
kn.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [32]:
x_new=np.array([[5,2.9,1,0.2]])
print("x_new.shape:{}".format(x_new.shape))


x_new.shape:(1, 4)


Here we are writting code to predict:

In [33]:
prediction =kn.predict(x_new)
print("Prediction:{}".format(prediction))
print("Predicted target name:{}".format(
    iris_dataset['target_names'][prediction]
))

Prediction:[0]
Predicted target name:['setosa']


Here we are evaluting the model:

In [36]:
y_pred=kn.predict(x_test)
print("Test set predictions:\n{}".format(y_pred))

Test set predictions:
[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


In [35]:
print("Test set score: {}".format(np.mean(y_pred==y_test)))

Test set score: 0.9736842105263158
